SEED_DATA = {
    "drafts": [
        {"id": 1, "title": "Автоматизация заявок учебного центра", "description": "Заявки приходят из разных каналов, менеджеры забывают отвечать. Хотим автоматизировать.", "industry": "Образование"},
        {"id": 2, "title": "Чат-бот для абитуриентов", "description": "Нужен бот, который отвечает на частые вопросы по поступлению.", "industry": "EdTech"},
        {"id": 3, "title": "Анализ посещаемости курсов", "description": "Есть выгрузки из Zoom, хотим видеть аналитику по студентам.", "industry": "Образование"},
        {"id": 4, "title": "Геймификация сдачи ДЗ", "description": "Студенты ленятся сдавать домашку вовремя, нужна система ачивок.", "industry": "EdTech"},
        {"id": 5, "title": "Маркетплейс менторов", "description": "Платформа для поиска экспертов и записи на консультации.", "industry": "Образование"},
    ],
    "tasks": [
        {
            "id": 101,
            "title": "Сокращение потерь заявок в учебном центре",
            "context": "Заявки из Instagram и сайта теряются, нет единой системы учета.",
            "need": "Нужно автоматизировать сбор заявок в единый дашборд.",
            "description": "Автоматизация сбора и обработки заявок для учебного центра.",
            "data_description": "Обезличенный реестр заявок за 3 месяца (Excel-таблица, 500 строк).",
            "expected_result": "Веб-интерфейс для 2 менеджеров с уведомлениями и статусами заявок.",
            "success_criteria": "Время обработки заявки сокращено до 10 минут, 0 потерянных лидов.",
            "deadline": "2 недели",
            "target_users": "2 менеджера по продажам и администратор центра.",
            "author_name": "Александр К. (Учебный центр)",
            "interaction_format": "Telegram: @edu_center_admin, еженедельный созвон",
            "status": "open",
            "score": 100,
            "readiness_level": "Приоритетная",
        },
        {
            "id": 102,
            "title": "ИИ-тренажер разговорного английского",
            "context": "Студентам не хватает практики говорения между уроками.",
            "need": "Разработать голосового бота для диалогов.",
            "description": "Интерактивный бот для практики разговорной речи.",
            "data_description": "Список из 50 популярных тем и скрипты диалогов.",
            "expected_result": "Голосовой бот в Telegram.",
            "success_criteria": "Студент проходит минимум 3 диалога в неделю.",
            "deadline": "3 недели",
            "target_users": "Студенты уровня A2-B1.",
            "author_name": "Елена М. (Языковая школа)",
            "interaction_format": "Email: partner@engschool.kz",
            "status": "open",
            "score": 85,
            "readiness_level": "Готовая",
        },
        {
            "id": 103,
            "title": "Платформа автопроверки лабораторных работ",
            "context": "Преподаватели тратят много времени на ручную проверку кода.",
            "need": "Автоматизировать запуск тестов.",
            "description": "Система автоматической проверки кода студентов.",
            "data_description": "Тестовые авто-тесты на Python.",
            "expected_result": "Система автопроверки тестов.",
            "success_criteria": "",
            "deadline": "1 месяц",
            "target_users": "Студенты IT-специальностей.",
            "author_name": "Данияр (IT-факультет)",
            "interaction_format": "Telegram: @it_dean",
            "status": "open",
            "score": 60,
            "readiness_level": "Рабочая",
        },
        {
            "id": 104,
            "title": "Дашборд успеваемости школы",
            "context": "Нужен визуальный отчет для директора.",
            "need": "Сделать графики успеваемости.",
            "description": "Панель аналитики для руководства.",
            "data_description": "",
            "expected_result": "Графики и диаграммы.",
            "success_criteria": "",
            "deadline": "1 месяц",
            "target_users": "Директор школы.",
            "author_name": "Школа №15",
            "interaction_format": "",
            "status": "draft",
            "score": 30,
            "readiness_level": "Черновик",
        },
        {
            "id": 105,
            "title": "Приложение для школьной столовой",
            "context": "Очереди в буфете на перемене.",
            "need": "Электронный предзаказ еды.",
            "description": "Модуль онлайн-заказа блюд.",
            "data_description": "",
            "expected_result": "Модуль предзаказа еды.",
            "success_criteria": "",
            "deadline": "",
            "target_users": "Школьники.",
            "author_name": "ИП ФудСервис",
            "interaction_format": "",
            "status": "draft",
            "score": 30,
            "readiness_level": "Черновик",
        },
    ],
    "teams": [
        {"id": 1, "name": "Burkit Team", "interests": ["AI", "EdTech", "Web"], "skills": ["Python", "FastAPI", "JS"], "tech": "Fullstack"},
        {"id": 2, "name": "CyberNomads", "interests": ["Mobile", "UI/UX"], "skills": ["Flutter", "Figma"], "tech": "Mobile"},
        {"id": 3, "name": "DataWizards", "interests": ["Data Science", "Analytics"], "skills": ["Pandas", "SQL", "Python"], "tech": "Data"},
        {"id": 4, "name": "DevSquad", "interests": ["Web Dev", "Backend"], "skills": ["Node.js", "React"], "tech": "Fullstack"},
        {"id": 5, "name": "CodeCraft", "interests": ["Bots", "Automation"], "skills": ["Python", "Telegram API"], "tech": "Backend"},
    ],
    "applications": [
        {
            "id": 1,
            "task_id": 101,
            "team_id": 1,
            "team_name": "Burkit Team",
            "idea": "Веб-сервис на FastAPI + JS с интеграцией Telegram-бота для мгновенных уведомлений менеджеров.",
            "plan": "1. Проектирование БД (1 день)\n2. Разработка UI (3 дня)\n3. Интеграция с ботом (2 дня)",
            "deadline": "2 недели",
            "prototype_url": "https://github.com/burkit-team/prototype-demo",
            "status": "Выбрана",
        },
        {
            "id": 2,
            "task_id": 101,
            "team_id": 2,
            "team_name": "CyberNomads",
            "idea": "Мобильное приложение для менеджеров на Flutter.",
            "plan": "Разработка UI и подключение к бэкенду.",
            "deadline": "3 недели",
            "prototype_url": "https://figma.com/file/demo",
            "status": "На рассмотрении",
        },
        {
            "id": 3,
            "task_id": 102,
            "team_id": 5,
            "team_name": "CodeCraft",
            "idea": "Telegram-бот с распознаванием речи через Whisper API.",
            "plan": "Создание бота и настройка диалоговых сценариев.",
            "deadline": "2 недели",
            "prototype_url": "https://t.me/demo_eng_bot",
            "status": "На рассмотрении",
        },
        {
            "id": 4,
            "task_id": 103,
            "team_id": 3,
            "team_name": "DataWizards",
            "idea": "Микросервис в Docker, который автоматически прогоняет pytest.",
            "plan": "Разработка раннера тестов и дашборда результатов.",
            "deadline": "3 недели",
            "prototype_url": "https://github.com/datawizards/autocheck-demo",
            "status": "На рассмотрении",
        },
        {
            "id": 5,
            "task_id": 102,
            "team_id": 4,
            "team_name": "DevSquad",
            "idea": "Веб-приложение с аудио-тренажером на WebRTC.",
            "plan": "Верстка веб-интерфейса и подключение аудио-модуля.",
            "deadline": "4 недели",
            "prototype_url": "https://devsquad-demo.vercel.app",
            "status": "На рассмотрении",
        },
    ],
}
