SEED_DATA = {
    "drafts": [
        {
            "id": 1,
            "title": "Автоматизация заявок учебного центра",
            "raw_text": "Заявки приходят из разных каналов, менеджеры забывают отвечать. Хотим автоматизировать.",
            "industry": "Образование",
        },
        {
            "id": 2,
            "title": "Чат-бот для абитуриентов",
            "raw_text": "Нужен бот, который отвечает на частые вопросы по поступлению.",
            "industry": "EdTech",
        },
        {
            "id": 3,
            "title": "Анализ посещаемости курсов",
            "raw_text": "Есть выгрузки из Zoom, хотим видеть аналитику по студентам.",
            "industry": "Образование",
        },
        {
            "id": 4,
            "title": "Геймификация сдачи ДЗ",
            "raw_text": "Студенты ленится сдавать домашку вовремя, нужна система ачивок.",
            "industry": "EdTech",
        },
        {
            "id": 5,
            "title": "Маркетплейс менторов",
            "raw_text": "Платформа для поиска экспертов и записи на консультации.",
            "industry": "Образование",
        },
    ],
    "tasks": [
        {
            "id": 101,
            "title": "Сокращение потерь заявок в учебном центре",
            "context_need": "Заявки из Instagram и сайта теряются, нет единой системы учета. Нужно автоматизировать сбор заявок в единый дашборд.",
            "data_materials": "Обезличенный реестр заявок за 3 месяца (Excel-таблица, 500 строк).",
            "expected_result": "Веб-интерфейс для 2 менеджеров с уведомлениями и статусами заявок.",
            "success_criteria": "Время обработки заявки сокращено до 10 минут, 0 потерянных лидов.",
            "constraints": "Срок разработки — 2 недели, стек Python/React.",
            "target_users": "2 менеджера по продажам и администратор центра.",
            "business_contact": "Telegram: @edu_center_admin",
            "score": 100,
            "status": "Приоритетная",
        },
        {
            "id": 102,
            "title": "ИИ-тренажер разговорного английского",
            "context_need": "Студентам не хватает практики говорения между уроками.",
            "data_materials": "Список из 50 популярных тем и скрипты диалогов.",
            "expected_result": "Голосовой бот в Telegram.",
            "success_criteria": "Студент проходит минимум 3 диалога в неделю.",
            "constraints": "Использовать бесплатно доступные API.",
            "target_users": "Студенты уровня A2-B1.",
            "business_contact": "Email: partner@engschool.kz",
            "score": 85,
            "status": "Готовая",
        },
        {
            "id": 103,
            "title": "Платформа автоматической проверки лабораторных работ",
            "context_need": "Преподаватели тратят много времени на ручную проверку кода.",
            "data_materials": "Тестовые авто-тесты на Python.",
            "expected_result": "Система автопроверки тестов.",
            "success_criteria": "",
            "constraints": "Docker контейнеризация.",
            "target_users": "Студенты IT-специальностей.",
            "business_contact": "Telegram: @it_dean",
            "score": 60,
            "status": "Рабочая",
        },
        {
            "id": 104,
            "title": "Дашборд успеваемости школы",
            "context_need": "Нужен визуальный отчет для директора.",
            "data_materials": "",
            "expected_result": "Графики и диаграммы.",
            "success_criteria": "",
            "constraints": "Срок 1 месяц.",
            "target_users": "Директор школы.",
            "business_contact": "",
            "score": 30,
            "status": "Черновик",
        },
        {
            "id": 105,
            "title": "Мобильное приложение для школьной столовой",
            "context_need": "Очереди в буфете на перемене.",
            "data_materials": "",
            "expected_result": "Модуль предзаказа еды.",
            "success_criteria": "",
            "constraints": "",
            "target_users": "Школьники.",
            "business_contact": "",
            "score": 30,
            "status": "Черновик",
        },
    ],
    "teams": [
        {
            "id": 1,
            "name": "Burkit Team",
            "interests": ["AI", "EdTech", "Web"],
            "skills": ["Python", "FastAPI", "JS"],
            "tech": "Fullstack",
        },
        {
            "id": 2,
            "name": "CyberNomads",
            "interests": ["Mobile", "UI/UX"],
            "skills": ["Flutter", "Figma"],
            "tech": "Mobile",
        },
        {
            "id": 3,
            "name": "DataWizards",
            "interests": ["Data Science", "Analytics"],
            "skills": ["Pandas", "SQL", "Python"],
            "tech": "Data",
        },
        {
            "id": 4,
            "name": "DevSquad",
            "interests": ["Web Dev", "Backend"],
            "skills": ["Node.js", "React"],
            "tech": "Fullstack",
        },
        {
            "id": 5,
            "name": "CodeCraft",
            "interests": ["Bots", "Automation"],
            "skills": ["Python", "Telegram API"],
            "tech": "Backend",
        },
    ],
    "applications": [
        {
            "id": 1,
            "task_id": 101,
            "team_id": 1,
            "team_name": "Burkit Team",
            "idea": "Предлагаем сделать веб-сервис на FastAPI + JS с интеграцией Telegram-бота для мгновенных уведомлений менеджеров.",
            "plan": "1. Проектирование БД (1 день)\n2. Разработка верстки (3 дня)\n3. Интеграция с ботом (2 дня)\n4. Тестирование (2 дня)",
            "timeline": "2 недели",
            "proto_link": "https://github.com/burkit-team/prototype-demo",
            "status": "Выбрана",
        },
        {
            "id": 2,
            "task_id": 101,
            "team_id": 2,
            "team_name": "CyberNomads",
            "idea": "Сделаем мобильное приложение для менеджеров на Flutter.",
            "plan": "Разработка UI и подключение к бэкенду.",
            "timeline": "3 недели",
            "proto_link": "https://figma.com/file/demo",
            "status": "На рассмотрении",
        },
    ],
}
