"""Тестовые данные для первого запуска локальной базы Burkit."""

SEED_DATA = {
    "tasks": [
        {
            "id": 1,
            "author_name": "Алия Садыкова",
            "language": "ru",
            "description": "Хотим сократить время обработки обращений клиентов.",
            "title": "Анализ обращений клиентов",
            "context": None,
            "need": None,
            "users": None,
            "data_description": None,
            "constraints": None,
            "expected_result": None,
            "success_criteria": None,
            "contact": None,
            "interaction_format": None,
            "status": "draft",
        },
        {
            "id": 2,
            "author_name": "Данияр Омаров",
            "language": "ru",
            "description": "Нужен сервис для помощи студентам в выборе практики.",
            "title": "Подбор студенческой практики",
            "context": None,
            "need": None,
            "users": None,
            "data_description": None,
            "constraints": None,
            "expected_result": None,
            "success_criteria": None,
            "contact": None,
            "interaction_format": None,
            "status": "draft",
        },
        {
            "id": 3,
            "author_name": "Ирина Ким",
            "language": "ru",
            "description": "Ищем способ контролировать остатки товаров.",
            "title": "Контроль складских остатков",
            "context": None,
            "need": None,
            "users": None,
            "data_description": None,
            "constraints": None,
            "expected_result": None,
            "success_criteria": None,
            "contact": None,
            "interaction_format": None,
            "status": "draft",
        },
        {
            "id": 4,
            "author_name": "Марат Тлеубаев",
            "language": "ru",
            "description": "Нужно упростить запись жителей на городские услуги.",
            "title": "Онлайн-запись на городские услуги",
            "context": None,
            "need": None,
            "users": None,
            "data_description": None,
            "constraints": None,
            "expected_result": None,
            "success_criteria": None,
            "contact": None,
            "interaction_format": None,
            "status": "draft",
        },
        {
            "id": 5,
            "author_name": "Айгерим Нурланова",
            "language": "ru",
            "description": "Хотим собирать обратную связь после обучения.",
            "title": "Обратная связь по курсам",
            "context": None,
            "need": None,
            "users": None,
            "data_description": None,
            "constraints": None,
            "expected_result": None,
            "success_criteria": None,
            "contact": None,
            "interaction_format": None,
            "status": "draft",
        },
        {
            "id": 101,
            "author_name": "Алия Садыкова",
            "language": "ru",
            "description": "Классифицировать обращения и выделять срочные случаи.",
            "title": "AI-классификация обращений клиентов",
            "context": "Операторы вручную разбирают около 500 обращений в день.",
            "need": "Нужно автоматически определять тему и приоритет обращения.",
            "users": "Операторы контакт-центра и руководитель смены.",
            "data_description": "Обезличенная выборка из 10 000 обращений в CSV.",
            "constraints": "Прототип не должен отправлять данные во внешние хранилища.",
            "expected_result": "API и экран с категорией, приоритетом и кратким резюме.",
            "success_criteria": "Точность категории не ниже 80% на тестовой выборке.",
            "contact": "Владелец продукта и два оператора контакт-центра.",
            "interaction_format": "Два интервью и финальная демонстрация.",
            "status": "open",
        },
        {
            "id": 102,
            "author_name": "Данияр Омаров",
            "language": "ru",
            "description": "Подбирать студентам подходящие места практики.",
            "title": "Рекомендации мест практики",
            "context": "Студенты просматривают длинный список предложений вручную.",
            "need": "Нужен подбор по навыкам, интересам и доступности.",
            "users": "Студенты и координаторы практики.",
            "data_description": "Анкеты студентов и каталог компаний в JSON.",
            "constraints": "Решение должно объяснять причину каждой рекомендации.",
            "expected_result": "Пять ранжированных рекомендаций для выбранного профиля.",
            "success_criteria": "Не менее трёх релевантных вариантов из пяти.",
            "contact": "Координатор карьерного центра.",
            "interaction_format": "Еженедельная встреча на 30 минут.",
            "status": "open",
        },
        {
            "id": 103,
            "author_name": "Ирина Ким",
            "language": "ru",
            "description": "Предсказывать дефицит товаров на складе.",
            "title": "Прогноз складских остатков",
            "context": "Популярные позиции заканчиваются раньше плановой закупки.",
            "need": "Нужно заранее предупреждать менеджера о возможном дефиците.",
            "users": "Менеджеры склада и специалисты по закупкам.",
            "data_description": "История продаж и остатков за последние 12 месяцев.",
            "constraints": "Прототип работает на локальном CSV без интеграции с ERP.",
            "expected_result": "Таблица рисков дефицита на ближайшие семь дней.",
            "success_criteria": None,
            "contact": "Руководитель склада.",
            "interaction_format": "Одна консультация и приёмка результата.",
            "status": "open",
        },
        {
            "id": 104,
            "author_name": "Марат Тлеубаев",
            "language": "ru",
            "description": "Создать понятную запись жителей на городские услуги.",
            "title": "Умная запись на городские услуги",
            "context": "Жители не понимают, какое окно и пакет документов выбрать.",
            "need": "Нужен помощник, который уточнит запрос и предложит свободное время.",
            "users": "Жители города и сотрудники центра обслуживания.",
            "data_description": "Тестовый перечень услуг, документов и временных слотов.",
            "constraints": "Без подключения к государственным системам в рамках MVP.",
            "expected_result": "Рабочий сценарий от вопроса пользователя до подтверждения записи.",
            "success_criteria": "Пользователь завершает тестовую запись менее чем за три минуты.",
            "contact": "Представитель центра обслуживания.",
            "interaction_format": "Связь в чате в рабочее время.",
            "status": "open",
        },
        {
            "id": 105,
            "author_name": "Айгерим Нурланова",
            "language": "ru",
            "description": "Анализировать отзывы участников образовательных программ.",
            "title": "Аналитика обратной связи по курсам",
            "context": "Методисты вручную читают сотни свободных комментариев.",
            "need": "Нужно находить повторяющиеся проблемы и сильные стороны курса.",
            "users": "Методисты и руководители образовательных программ.",
            "data_description": "Обезличенные оценки и комментарии из анкет.",
            "constraints": "Интерфейс и результат должны быть на русском языке.",
            "expected_result": "Сводка тем, тональности и примеров комментариев.",
            "success_criteria": "Методист подтверждает корректность не менее 80% найденных тем.",
            "contact": "Руководитель методического отдела.",
            "interaction_format": "Установочная встреча и демонстрация прототипа.",
            "status": "open",
        },
    ],
    "teams": [
        {"id": 1, "name": "Burkit", "interests": ["AI", "образование"], "skills": ["Python", "FastAPI", "React"], "technology": "OpenAI, SQLite"},
        {"id": 2, "name": "Data Nomads", "interests": ["аналитика", "ритейл"], "skills": ["Python", "Pandas", "ML"], "technology": "scikit-learn, Streamlit"},
        {"id": 3, "name": "Qadam", "interests": ["GovTech", "UX"], "skills": ["TypeScript", "React", "Figma"], "technology": "React, FastAPI"},
        {"id": 4, "name": "Orda AI", "interests": ["NLP", "клиентский сервис"], "skills": ["Python", "NLP", "Docker"], "technology": "OpenAI, PostgreSQL"},
        {"id": 5, "name": "Sana Lab", "interests": ["EdTech", "рекомендации"], "skills": ["Python", "JavaScript", "Data Science"], "technology": "FastAPI, React"},
    ],
    "proposals": [
        {"id": 1, "task_id": 101, "team_id": 4, "team_name": "Orda AI", "idea": "Классификатор с кратким объяснением приоритета.", "plan": "Очистить выборку, настроить промпт, проверить метрики, собрать демо.", "deadline": "3 дня", "prototype_url": None, "status": "pending"},
        {"id": 2, "task_id": 102, "team_id": 5, "team_name": "Sana Lab", "idea": "Ранжирование практик по совпадению навыков и интересов.", "plan": "Подготовить признаки, реализовать рейтинг, показать пять рекомендаций.", "deadline": "3 дня", "prototype_url": None, "status": "pending"},
        {"id": 3, "task_id": 103, "team_id": 2, "team_name": "Data Nomads", "idea": "Прогноз спроса и список товаров с риском дефицита.", "plan": "Исследовать данные, построить базовый прогноз, вывести таблицу рисков.", "deadline": "4 дня", "prototype_url": None, "status": "pending"},
        {"id": 4, "task_id": 104, "team_id": 3, "team_name": "Qadam", "idea": "Диалоговый мастер выбора услуги и времени записи.", "plan": "Описать сценарий, сделать форму уточнений, подключить тестовые слоты.", "deadline": "3 дня", "prototype_url": None, "status": "pending"},
        {"id": 5, "task_id": 105, "team_id": 1, "team_name": "Burkit", "idea": "Группировка отзывов по темам с краткой сводкой.", "plan": "Подготовить данные, вызвать AI, проверить JSON и собрать карточки результата.", "deadline": "3 дня", "prototype_url": None, "status": "pending"},
    ],
}
